### ISSUE TITLE
Negative margins

### ISSUE THREAD

**Issue by lkostrowski** [saleor/macaw-ui#563] opened 2023-09-04 12:30 UTC
### What I'm trying to achieve

In CSS negative margin is sometimes useful, eg:

```
<Box padding={5}>
  <Divider padding={-5} />
</Box>
```

This snippet doesn't work because negative margin can't be set. However it will be handy if its possible - so child element can stretch to override parent padding. 

This can be done other way around but requires a lot of boilerplate.

Setting `__margin` doesn't work because we opt-out from a design token. So first I'd need to extract token value, then calculate it `*5`, then assign its value to `__margin`

### Describe a proposed solution

Add mirrored spacing values that will be negative (-1, -2, -3 etc)

**Comment by krzysztofzuraw** [comment] 2023-09-08 07:12
Duplicate of https://github.com/saleor/macaw-ui/issues/499

**Closed by krzysztofzuraw** 2023-09-08 07:12 UTC
Labels: next
