### ISSUE TITLE
[RFC]: Reduce fragmentation of typography scale

### ISSUE THREAD

**Issue by timuric** [saleor/macaw-ui#574] opened 2023-09-15 12:14 UTC
### Short description of the feature

- Introduce a single typography scale to make add harmony and consistency

Here is example of typography scale fragmentation that is observed in dashboard:

<img width="246" alt="image" src="https://github.com/saleor/macaw-ui/assets/4006792/687d2e17-2dd5-48f9-8318-23c9c468c6df">

 

### Full description

Design document would be added here

### Acceptance Criteria

- [] Typography scale follows predictable steps across all components
- [] Ensure significant contrast between each step to make variants meaningful
- [] Prove that selected density is a good choice for all components

**Comment by krzysztofzuraw** [comment] 2024-01-19 08:42
Duplicate of https://github.com/saleor/macaw-ui/issues/574

**Closed by krzysztofzuraw** 2024-01-19 08:42 UTC
Labels: breaking, backlog
